language: node_js
node_js:
    - 'lts/*'
sudo: false
cache: npm
script:
    - ./validate.sh
    - npm run lint:check
    - npm run build
after_success:
    - ./comment.sh
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository
    keep-history: true
    on:
        branch: master
    local-dir: public
